### ISSUE TITLE
Setup breaks if "Mail From" value includes a space

### ISSUE THREAD

**Issue by stefnnn** [webreinvent/vaah-docs#176]
I tried to install vaah-cms with the installer and entered a full name into the "From Name" field. The server crashed on the next screen, because the .env file contained a whitespace

```
MAIL_FROM_NAME=Some Name
```

Probably it would be save to wrap all values into double quotes, or at least those that can contain whitespace.

**Comment by stefnnn** [comment]
Sorry, this issue was supposed to go into vaah-cms, feel free to move it over.

**Comment by themodernpk** [comment]
@stefnnn makes sense, will address this in the next release.

**Comment by themodernpk** [comment]
@stefnnn forgot to close this issue, this is already resolved.
