### ISSUE TITLE
Active buttons in setup look like inactive buttons

### ISSUE THREAD

**Issue by stefnnn** [webreinvent/vaah-docs#177]
While I like the design of the setup screens, it took me a while to figure out, that the buttons ("Test Database Connection") are actually active buttons ready to be clicked. I think they should have a primary background color to indicate, that they should be clicked next.

Also, even tough I have tested the database successfully, there was still an info text at the bottom, saying that I need to test the database before proceeding.

**Comment by stefnnn** [comment]
Sorry, this issue was supposed to go into vaah-cms, feel free to move it over.

**Comment by themodernpk** [comment]
@stefnnn forgot to close this issue, this is already resolved.
